version: '3.8'

services:
  mongo:
    image: mongo
    container_name: Mongo
    ports:
      - "28017:27017"
    networks:
      - Mongo-Network
    environment:
      MONGO_INITDB_ROOT_USERNAME: siam
      MONGO_INITDB_ROOT_PASSWORD: redapple
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: Mongo-Express
    ports:
      - "8081:8081"
    networks:
      - Mongo-Network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: redapple
      ME_CONFIG_MONGODB_ADMINPASSWORD: lavista
      ME_CONFIG_MONGODB_URL: mongodb://redapple:lavista@mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  Mongo-Network:
    driver: bridge